vim.keymap.set("n", "<leader>g", ":G")
vim.keymap.set("n", "<leader>gsa", ":G status")
vim.keymap.set("n", "<leader>gi", ":G init")
vim.keymap.set("n", "<leader>gc", ":G commit")
vim.keymap.set("n", "<leader>ga", ":G add")
vim.keymap.set("n", "<leader>gps", ":G push")
vim.keymap.set("n", "<leader>gpl", ":G pull")
vim.keymap.set("n", "<leader>gm", ":G merge")
vim.keymap.set("n", "<leader>gr", ":G restore")
vim.keymap.set("n", "<leader>gst", ":G stash")
vim.keymap.set("n", "<leader>gsp", ":G stash pop")
vim.keymap.set("n", "<leader>gb", ":G branch")
vim.keymap.set("n", "<leader>gl", ":G log")
vim.keymap.set("n", "<leader>gch", ":G checkout")
vim.keymap.set("n", "<leader>grb", ":G rebase")
