vim.keymap.set("n", "<leader>g", ":G<cr>")
vim.keymap.set("n", "<leader>gcl", ":G clone")
vim.keymap.set("n", "<leader>gi", ":G init<cr>")
vim.keymap.set("n", "<leader>ga", ":G add")
vim.keymap.set("n", "<leader>gc", ":G commit<cr>")
vim.keymap.set("n", "<leader>gsa", ":G status<cr>")
vim.keymap.set("n", "<leader>gd", ":G diff<cr>")
vim.keymap.set("n", "<leader>grm", ":G rm")
vim.keymap.set("n", "<leader>gps", ":G push")
vim.keymap.set("n", "<leader>gpl", ":G pull")
vim.keymap.set("n", "<leader>gm", ":G merge")
vim.keymap.set("n", "<leader>gr", ":G restore")
vim.keymap.set("n", "<leader>gst", ":G stash<cr>")
vim.keymap.set("n", "<leader>gsp", ":G stash pop<cr>")
vim.keymap.set("n", "<leader>gb", ":G branch")
vim.keymap.set("n", "<leader>gl", ":G log<cr>")
vim.keymap.set("n", "<leader>gch", ":G checkout")
vim.keymap.set("n", "<leader>grb", ":G rebase")
